### ISSUE TITLE
Is delta sorting being used, and is it stable?

### ISSUE THREAD

**Issue by Gitoffthelawn** [heftig/sort-bookmarks#14]
According to [this review](https://addons.mozilla.org/firefox/addon/auto-sort-bookmarks/reviews/1456174/) of Sort Bookmarks main "competitor" Auto-Sort Bookmarks, delta sorting might be used in this extension.

The author of Auto-Sort Bookmarks, whom I also respect, implies that delta sorting might be less stable.

Bookmarks stability has been a general issue in Firefox in the past (seems to be resolved now), and the last thing I want to do is introduce any instability, as I don't want to lose or corrupt any bookmarks.

Do you have any feedback, comments, opinions, clarifications, or thoughts on this?

**Comment by heftig** [comment]
Sorting as a reaction to a change ("Always keep sorted") sorts only a single folder. The same applies when a single folder is manually sorted. Otherwise ("Sorting all bookmarks") the entire tree is sorted recursively.

I'm not sure what they mean by "delta sorting". The extension doesn't keep a cache of the tree state, and neither does it attempt an insertion sort of a single bookmark on a change.

**Comment by Gitoffthelawn** [comment]
Ah, it sounds like this extension isn't using delta sorting.

To ensure clarity, when this extension sorts a folder, it sorts the entire folder, without exception, correct?

If the answer is "Yes", then it isn't using any delta sorting.  :)

**Comment by heftig** [comment]
Correct.

**Comment by Gitoffthelawn** [comment]
Great!  Thank you!
